### ISSUE TITLE
Multiple Processes not recognized

### ISSUE THREAD

**Issue by lajawi** [djkato/DRP_Creative#14]
As of writing this, when I have multiple projects open (e.g. a Photoshop file, and a Substance Painter one), only the one I first opened shows up.

**Comment by djkato** [comment]
I cannot tell which you're working in programmatically. Discord doesn't show multiple activities either, and if I send discord all of the open apps, discord doesn't show the last updated one anyways cause of their bugs. https://github.com/discord/discord-rpc/issues/217. 

Sadly this is both out of my control and my interest, as I'm now using linux and don't use this program anymore. Sorry for the inconvenience.

**Comment by djkato** [comment]
@lajawi If you only use adobe, consider using this plugin a friend of mine made. Works wayy better for adobe programs: https://github.com/teeteeteeteetee/adobe-discord-rpc

**Comment by lajawi** [comment]
> Discord doesn't show multiple activities either

From my experience, multiple activities simultaneously activities just works fine. They were each managed by their own extensions or programs, however.

> If you only use adobe, consider using this plugin a friend of mine made. Works wayy better for adobe programs: https://github.com/teeteeteeteetee/adobe-discord-rpc

I'll definitely look at it, as the other programs are either covered by their own RPC extensions, or not of interest to me.

Thanks for your answers!
