### ISSUE TITLE
can you please remove the portfolio section

### ISSUE THREAD

**Issue by Geovenchy** [djkato/DRP_Creative#2]
or atleast have as an option

**Comment by djkato** [comment]
@Geovenchy What would you like to see instead of it? Or just leave that field blank?

**Comment by Geovenchy** [comment]
nothing lol @djkato is looks like an official discord pressence without it. or atleast if you can add the buttons instead of just a plain url.

**Comment by djkato** [comment]
@Geovenchy 
![image](https://user-images.githubusercontent.com/25299243/215338582-5dbbcf19-4a98-4cfb-9dd5-8b99e9017156.png)
Hello! Sorry it took so long, but I finally got around to it :)
You can find the updated version in releases. Add the new exe to start up, and add the following line to your .drp_config:
```js
HIDE_PORTFOLIO_ROW:{
yes
}
```
Let me know if it works, cheers!
