### ISSUE TITLE
Can you add support for Zbrush?

### ISSUE THREAD

**Issue by MataPuelc0s** [djkato/DRP_Creative#3]
Can you add Zbrush App to the supported list?

**Comment by djkato** [comment]
Hello, sure I'll look into it when I find time :)

**Comment by djkato** [comment]
@MataPuelc0s I do not own Zbrush and the trial would probably not give me accurate results. Would you be willing to run some scripts while running Zbrush for me and send me their outputs, so I can tune DRPC to work correctly with it? If yes please reach out to either Djkáťo#7054 on discord or we can do it directly here. It would help a lot, cheers
