### ISSUE TITLE
Config keeps changing / resetting.

### ISSUE THREAD

**Issue by Geovenchy** [djkato/DRP_Creative#7]
im not sure what im doing wrong but the config changes back to default randomly. 

i have to keep adding the hide portfolio code in.

**Comment by djkato** [comment]
Sorry about that, I'll investigate soon!

**Comment by Geovenchy** [comment]
or maybe im just not understanding how this works.

if you can just make this the default, that would be perfect. i dont think anybody needs the portfolio section , and if so , make it where it shows the discord presence button instead of just the text so people can just click on it .

Default should be Woking on [program name ] Project . if you can do that, that'll be better than having to keep on clickin on Dont show current project

![image](https://github.com/djkato/DRP_Creative/assets/30054703/cd0742eb-aab7-41b1-ab31-520ac213d8c9)

**Comment by djkato** [comment]
The config should not change back, so if it does reset it's not intended behaviour and I'll try to fix it. 
While I understand that you don't need the portfolio row, I like it and I mainly developed this program for myself, so it's staying the default cause I'm selfish :D.

**Comment by djkato** [comment]
And as for the project name, rarely any of my users see the need in hiding project names, it feels more engaging too. Though if you find yourself clicking hide project instead of showing them, I will find a way to make it a setting where that list inverts from hide projects to show only projects

**Comment by Geovenchy** [comment]
understood! no problem

**Comment by djkato** [comment]
Please give the [v1.0.3](https://github.com/djkato/DRP_Creative/releases/tag/v1.0.3) release a try, next time you run the app it should ask for an update. I reworked the whole config file system as it was lacking anyways, and added "Exclusive vs Include" options on the word list. If an issue appears again feel free to reopen this issue or make a new one. Cheers  .)
